version: '2'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/apipromova
    depends_on:
      - salic_db
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
      - PYTHONIOENCODING=utf-8
      - DB_HOST=salic_db
      - DB_PORT=
      - DB_USER=
      - DB_PASSWORD=
    ports:
      - '5001:5001'

  salic_db:
    image: lappis/openconnect-globalprotect
    environment:
      - VPN_PASSWORD=
      - VPN_SERVER=
      - VPN_USER=
      - SERVICE_IP=
      - SERVICE_PORT=
    ports:
      - "9000:1435"
    privileged: true
    cap_add:
      - NET-ADMIN

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile_nginx
    ports:
      - "8080:8080"
      - "8043:8043"
    depends_on:
      - web
